# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Tue Jun 14 23:27:10 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(30, 80, 341, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(30, 120, 122, 70))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.translactionButton = QtWidgets.QPushButton(self.widget)
        self.translactionButton.setObjectName("translactionButton")
        self.verticalLayout_3.addWidget(self.translactionButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.setButton = QtWidgets.QPushButton(self.widget)
        self.setButton.setObjectName("setButton")
        self.verticalLayout_4.addWidget(self.setButton)
        self.widget1 = QtWidgets.QWidget(self.centralWidget)
        self.widget1.setGeometry(QtCore.QRect(30, 10, 178, 44))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSelect_file = QtWidgets.QAction(MainWindow)
        self.actionSelect_file.setObjectName("actionSelect_file")
        self.actionAbout_our = QtWidgets.QAction(MainWindow)
        self.actionAbout_our.setObjectName("actionAbout_our")
        self.actionAbout_Progrmas = QtWidgets.QAction(MainWindow)
        self.actionAbout_Progrmas.setObjectName("actionAbout_Progrmas")
        self.actionUser_Guide = QtWidgets.QAction(MainWindow)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.actionHyperion_setting = QtWidgets.QAction(MainWindow)
        self.actionHyperion_setting.setObjectName("actionHyperion_setting")
        self.menuMenu.addAction(self.actionSelect_file)
        self.menuMenu.addAction(self.actionHyperion_setting)
        self.menuAbout.addAction(self.actionAbout_our)
        self.menuAbout.addAction(self.actionAbout_Progrmas)
        self.menuAbout.addAction(self.actionUser_Guide)
        self.menuBar.addAction(self.menuMenu.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.translactionButton.setText(_translate("MainWindow", "Translation file"))
        self.setButton.setText(_translate("MainWindow", "Setting"))
        self.label.setText(_translate("MainWindow", "hyperion 3.2"))
        self.label_2.setText(_translate("MainWindow", "Base on hyperion 1.2 Kernel"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSelect_file.setText(_translate("MainWindow", "Select file"))
        self.actionAbout_our.setText(_translate("MainWindow", "About Our Group"))
        self.actionAbout_Progrmas.setText(_translate("MainWindow", "About Progrmas"))
        self.actionUser_Guide.setText(_translate("MainWindow", "User Guide"))
        self.actionHyperion_setting.setText(_translate("MainWindow", "Setting"))

